export const GET_STUDENT_EDIT = 'GET_STUDENT_EDIT';
export const STUDENT_EDITED_SUCCESS = 'STUDENT_EDITED_SUCCESS';
export const CREATE_STUDENT_SUCCESS = 'CREATE_STUDENT_SUCCESS';
export const SHOW_STUDENTS_SUCCESS = 'SHOW_STUDENTS_SUCCESS';
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS';
